POST https://localhost:7079/api/User/Login
Accept: application/json
###
POST https://localhost:7079/api/User/Register
Accept: application/json
###
GET https://localhost:7079/api/User/Validate
Accept: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYmYiOjE2ODIxODY3OTQsImV4cCI6MTY4MjE5NzU5NCwiaXNzIjoiQXV0aCBQcm92aWRlciIsImF1ZCI6IkF1dGggQ29uc3VtZXIifQ.ytQy1LN2eVGNgSYZKPkDaeL0D7di-ocemeGxIw1pZrUs_bb781Knn_nklrOgfMuG-uhl7WkG2QHyl13AJJE8J_vtBoQVnPIj51aoBDMkBw_WO3Duzgb43cpx2xuO6-L_Ga1hf_UxM1mNMAh-zSdvBDXQF4ceSjScuoT-5iU3rSDvj_GOIRYMGHgTbs5tz-0b2SDga2PcYTRKCD6EX52eoFM15P0oihHdhYfoJgP5Ag3CV9mkPzNpsi7iH6bcwwOTFPheI1Oo65xciRrXsOf-oslvMWZOqVXIBg2wySsOiHMGGStN0dXwc5elO8hXfdQQM10lcU6ok94Rwj0KXSFTGw
###